# Generated by Django 6.0.7 on 2026-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Click',
                'verbose_name_plural': 'Job Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
