# Generated by Django 6.0.3 on 2026-08-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('stores', '0003_store_affiliate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Click',
                'verbose_name_plural': 'Store Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
