# URL routing for the `jobseekers` app.
#
# All routes below are generated by DRF's SimpleRouter from JobSeekerViewSet and
# SavedJobViewSet, mounted (see project-level urls.py) under a prefix such as
# /api/jobseekers/. Every endpoint here requires authentication and is
# scoped to the requesting user's own data (job seekers only).
#
# profiles/ (JobSeekerViewSet):
#   GET    /profiles/          - list the current user's profile (effectively just their own row)
#   POST   /profiles/          - create a profile for the current user
#   GET    /profiles/{id}/     - retrieve a profile
#   PUT    /profiles/{id}/     - full update of a profile
#   PATCH  /profiles/{id}/     - partial update of a profile
#   DELETE /profiles/{id}/     - delete a profile
#   GET    /profiles/me/       - fetch the current user's profile (auto-created if missing)
#   PATCH  /profiles/me/       - update the current user's name/phone in one call
#
# saved-jobs/ (SavedJobViewSet):
#   GET    /saved-jobs/        - list the current user's saved/bookmarked jobs
#   POST   /saved-jobs/        - save (bookmark) a job post
#   GET    /saved-jobs/{id}/   - retrieve a single saved-job bookmark
#   DELETE /saved-jobs/{id}/   - remove (unsave) a bookmark
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()
router.register(r'profiles', views.JobSeekerViewSet, basename='jobseeker')
router.register(r'saved-jobs', views.SavedJobViewSet, basename='savedjob')

urlpatterns = [
    path('', include(router.urls)),
]
