# Generated by Django 6.0.7 on 2026-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('role_keyword', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
            },
        ),
    ]
