# Generated by Django 6.0.7 on 2026-07-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='jobseekers.jobseeker'),
        ),
    ]
