# Generated by Django 6.0.3 on 2026-08-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_store_owner',
            field=models.BooleanField(default=False),
        ),
    ]
