# Generated by Django 6.0.3 on 2026-07-24 15:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_portal', models.CharField(db_index=True, max_length=100)),
                ('job_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('organisation', models.CharField(max_length=500)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('civil_services', 'Civil Services (UPSC/MPSC)'), ('banking', 'Banking (IBPS/SBI)'), ('railway', 'Railway (RRB)'), ('police', 'Police & Defence'), ('teaching', 'Teaching & Education'), ('healthcare', 'Healthcare'), ('psu', 'Public Sector Undertaking'), ('state_govt', 'State Government'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=500)),
                ('vacancy_count', models.IntegerField(blank=True, null=True)),
                ('age_limit', models.CharField(blank=True, max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=200)),
                ('application_start', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('notification_pdf_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='govtjobs_go_search__65be81_gin')],
                'unique_together': {('source_portal', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='GovtJobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='govtjob_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
