# URL routing for the `jobs` app.
#
# All routes below are generated by DRF's SimpleRouter from JobPostViewSet
# and are mounted (see project-level urls.py) under a prefix such as /api/jobs/.
# Resulting endpoints (permissions enforced in JobPostViewSet.get_permissions):
#   GET    /               - list active job posts                  (anonymous - job seekers browsing)
#   POST   /               - create a job post                      (authenticated company user)
#   GET    /{id}/          - retrieve a single job post              (anonymous - job seekers browsing)
#   PUT    /{id}/          - full update of a job post               (authenticated - owning company)
#   PATCH  /{id}/          - partial update of a job post            (authenticated - owning company)
#   DELETE /{id}/          - delete a job post                       (authenticated - owning company)
#   GET    /my/            - list the current company's own posts    (authenticated company user)
#   POST   /{id}/track-click/ - record an "apply" click and return
#                               the redirect URL                     (anonymous - job seekers applying)
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()
router.register(r'', views.JobPostViewSet, basename='jobpost')

urlpatterns = [
    path('', include(router.urls)),
]
