# Generated by Django 6.0.3 on 2026-08-06 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='e.g. Full Stack Developer', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile', 'Mobile Apps'), ('design', 'Design & Creative'), ('writing', 'Content Writing'), ('data', 'Data & Analytics'), ('it_network', 'IT & Networking'), ('marketing', 'Digital Marketing'), ('legal', 'Legal & Finance'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('skills', models.JSONField(default=list, help_text="List of skill strings e.g. ['React', 'Node.js']")),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate in INR per hour', max_digits=8, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('not_available', 'Not Available')], db_index=True, default='available', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='freelancers/photos/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='freelancers.freelancerprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Review',
                'ordering': ['-created_at'],
                'unique_together': {('freelancer', 'reviewer')},
            },
        ),
    ]
