# Generated by Django 6.0.3 on 2026-07-24 15:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('tenders_found', models.IntegerField(default=0)),
                ('tenders_new', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_portal', models.CharField(db_index=True, max_length=100)),
                ('tender_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.CharField(max_length=500)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('civil', 'Civil Works'), ('it', 'IT & Software'), ('supply', 'Supply of Goods'), ('transport', 'Transport'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('defence', 'Defence'), ('power', 'Power & Energy'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('document_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('published_at', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('document_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tenders_ten_search__fee49a_gin')],
                'unique_together': {('source_portal', 'tender_id')},
            },
        ),
        migrations.CreateModel(
            name='TenderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
