# Generated by Django 6.0.3 on 2026-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Maharashtra Tenders'", max_length=200)),
                ('source_portal', models.CharField(db_index=True, help_text="Unique portal key used as dedup key in Tender/GovtJob, e.g. 'mahatenders.gov.in'", max_length=100, unique=True)),
                ('url', models.URLField(help_text='Listing page URL that the spider starts from')),
                ('source_type', models.CharField(choices=[('tender', 'Government Tender'), ('govt_job', 'Government Job')], db_index=True, max_length=20)),
                ('spider_name', models.CharField(help_text='Scrapy spider name to run for this portal (must exist in scrapers/spiders/)', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State this portal covers (leave blank for national/central portals)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scraper Source',
                'verbose_name_plural': 'Scraper Sources',
                'ordering': ['source_type', 'name'],
            },
        ),
    ]
