# Generated by Django 6.0.3 on 2026-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_scraper_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapersource',
            options={'ordering': ['name'], 'verbose_name': 'Scraper Source', 'verbose_name_plural': 'Scraper Sources'},
        ),
        migrations.RemoveField(
            model_name='scrapersource',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-set to domain if left blank.', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='source_portal',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-derived from URL domain. Becomes the dedup key in Tender records.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='spider_name',
            field=models.CharField(default='generic_tender', help_text="Scrapy spider to use. Default 'generic_tender' works for NIC eProcurement portals.", max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='state',
            field=models.CharField(blank=True, help_text='State this portal covers (leave blank for national portals).', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='url',
            field=models.URLField(help_text='Tender listing page URL (only field required)', unique=True),
        ),
    ]
