# Generated by Django 6.0.3 on 2026-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_simplify_scraper_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapersource',
            options={'ordering': ['source_type', 'name'], 'verbose_name': 'Scraper Source', 'verbose_name_plural': 'Scraper Sources'},
        ),
        migrations.AddField(
            model_name='scrapersource',
            name='source_type',
            field=models.CharField(choices=[('tender', 'Government Tender'), ('govt_job', 'Government Job')], db_index=True, default='tender', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='source_portal',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-derived from URL domain. Used as dedup key in Tender/GovtJob records.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='spider_name',
            field=models.CharField(blank=True, help_text='Scrapy spider name. Auto-set from source_type if left blank.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='url',
            field=models.URLField(help_text='Portal listing page URL (only required field)', unique=True),
        ),
    ]
