# Generated by Django 6.0.3 on 2026-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_add_source_type_to_scraper_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='reference_number',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
