# Generated by Django 6.0.3 on 2026-08-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('category', models.CharField(choices=[('marketplaces', 'General Marketplaces'), ('fashion', 'Fashion & Apparel'), ('footwear', 'Footwear'), ('electronics', 'Electronics & Mobiles'), ('grocery', 'Grocery & Quick Commerce'), ('beauty', 'Beauty & Personal Care'), ('pharmacy', 'Pharmacy & Health'), ('home', 'Home, Furniture & Decor'), ('jewellery', 'Jewellery'), ('books', 'Books & Stationery'), ('baby', 'Baby & Kids'), ('sports', 'Sports & Fitness'), ('eyewear', 'Eyewear & Watches'), ('refurbished', 'Refurbished & Second-Hand'), ('bags', 'Bags & Luggage'), ('global', 'Global (Ships to India)'), ('other', 'Other')], default='other', max_length=50)),
                ('website_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
    ]
