# Generated by Django 6.0.3 on 2026-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_locator_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('online', 'Online Store'), ('retail', 'Retail Chain')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
