# Generated by Django 6.0.3 on 2026-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_store_locator_url_store_store_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Pre-converted affiliate link (EarnKaro, etc.). Overrides automatic Amazon tag injection.', verbose_name='Affiliate URL'),
        ),
    ]
