# Generated by Django 6.0.3 on 2026-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_affiliate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='affiliate_network',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon Associates'), ('cuelinks', 'Cuelinks'), ('earnkaro', 'EarnKaro'), ('direct', 'Direct (no affiliate)')], help_text='Which affiliate network this store earns through. Shown as a badge on the shopping page.', max_length=20, verbose_name='Affiliate Network'),
        ),
    ]
